### ISSUE TITLE
Put line 34 - 41 to a private function to make the code more clearer?

### ISSUE THREAD

**Issue by liwentao** [liwentao/conversion-data-loader#1]
https://github.com/liwentao/conversion-data-loader/blob/1050bfd287e9e0f00cd976f89b9d3161457145be/CampaignTracker.swift#L34

**Comment by deerstalker** [comment]
Swift does not allow call self.privatefunction in initializer and other work arounds make this more complex. I'd like to deprioritize this.

**Comment by liwentao** [comment]
Agree
