### ISSUE TITLE
Should the backoff flag be an int?

### ISSUE THREAD

**Issue by liwentao** [liwentao/conversion-data-loader#3]
https://github.com/liwentao/conversion-data-loader/blob/1050bfd287e9e0f00cd976f89b9d3161457145be/CampaignTracker.swift#L102

The current backoff flag is a boolean, thus we couldn't do things like exponential backoff retry. Probably it would be better to make the backoff time configurable. For example, the 1st retry to backoff 1 second, the 2nd retry to backoff 3 second, and the 3rd retry to backoff 5 second.

**Comment by deerstalker** [comment]
Yes, it will be "icing on the cake". I will improve this later.

**Comment by deerstalker** [comment]
Both ios and android now support configurable back off time.
